import { e as e$1 } from '../../../chunks/when_ready.util-67a26b5e.js';
import { t } from '../../../chunks/inject_script.util-c32e5cad.js';
import { o } from '../../../chunks/storage-f52a9ff9.js';
import { s, l } from '../../../chunks/get_stream_details-d97c917a.js';
import { e } from '../../../chunks/style-inject.es-e19c9629.js';
import { o as o$1 } from '../../../chunks/index-fe22708a.js';
import '../../../chunks/browser-polyfill-1756fcfb.js';

async function h(){setInterval((async()=>{await async function(){const t=await o.settings.get("chatStyles"),e=l();return t&&e}()?document.body.setAttribute("data-mogul-chat-styles",""):document.body.removeAttribute("data-mogul-chat-styles");}),250);}e('/* Overwrite colors on verified/owner names */\nyt-live-chat-author-chip[is-highlighted] #author-name.owner.yt-live-chat-author-chip,\n#author-name.owner.yt-live-chat-author-chip {\n  color: var(--yt-live-chat-author-chip-owner-text-color) !important;\n}\n\nyt-live-chat-author-chip[is-highlighted] #author-name.yt-live-chat-author-chip {\n  color: var(--yt-live-chat-author-chip-verified-text-color) !important;\n}\n\n\nbody[data-mogul-chat-styles] #author-photo.yt-live-chat-text-message-renderer {\n\tdisplay: none;\n}\n\nbody[data-mogul-chat-styles] yt-live-chat-text-message-renderer {\n\tmin-height: 24px;\n}\n\nbody[data-mogul-chat-styles] yt-live-chat-author-chip {\n\tdirection: rtl;\n}\n\nbody[data-mogul-chat-styles] yt-live-chat-author-chip::before {\n\tcontent: ":";\n}\n\nbody[data-mogul-chat-styles] #author-name.member.yt-live-chat-author-chip,\n#author-name.moderator.yt-live-chat-author-chip {\n  font-weight: 800 !important;\n}\n\nbody[data-mogul-chat-styles] yt-live-chat-author-badge-renderer.yt-live-chat-author-chip {\n  margin: 0 4px 0 0 !important;\n}\n\n#message.yt-live-chat-text-message-renderer .emoji.yt-live-chat-text-message-renderer {\n  width: auto !important;\n  min-height: 28px !important;\n}\n'),o.settings.get("hideEmojiFountain").then((t=>{var e;t&&(null===(e=document.getElementById("reaction-control-panel-overlay"))||void 0===e||e.remove());})),e$1((()=>{t("legacy/injected/youtube/index.js"),o$1.settings.get("experimental").then((t$1=>{t$1&&t("legacy/injected/youtube/quick_actions.js","truffle-quick-actions");})),s()&&h();}));
